### ISSUE TITLE
Take Down Request

### ISSUE THREAD

**Issue by alexpoiry** [Dubsado/fontawesome-pro#1]
Hello,

I work security for Font Awesome. I like to give people the benefit of the doubt but you're just hosting our pro assets under our same name and didn't even remove our license information which clearly states this is not free software. If you look at the short version of the license it says "The Font Awesome Pro commercial license allows you to pay for FA Pro once, own
it, and use it just about everywhere you'd like." If you read the full license, you'll see just about everywhere doesn't include hosting it for free on GitHub.

This is pretty clearly a copyright violation. Before I file a DMCA, I'd like to give you a few days to take this repository down yourself. I don't want to be a jerk but we aren't a huge company like Microsoft our Google. We're just a few people trying to make some awesome icons and this really hurts us.

Please remove this. I'll give you a few days but then I'll be filing a DMCA with GitHub.

**Comment by brandonn1231** [comment]
Hi, thank you for reaching out to us about this issue. We will take the following steps next week to remedy this problem:
- make repo private
- rename repo

If there's anything else we can help with, please don't hesitate to contact us again!

**Comment by alexpoiry** [comment]
That should be sufficient.  Please comment when the modifications have been completed.

**Comment by alexpoiry** [comment]
It has been a week since your last comment.  Renaming and making a repository private should be a relatively quick process.  Is there some other issue preventing you from completing this request?

If I do not get a reply by approximately this time tomorrow, I will open another issue.

**Comment by dannydi12** [comment]
Hi @alexpoiry

We've been tied up with some other pressing incidents this week/last week that required all hands on deck. Please give us the time necessary to make these changes, we are a small team of developers. It's unfortunately not a relatively quick process to make the repository private because all our CI/CD pipelines need to be updated with Github access tokens to be able to access a private repo.

I will be taking over this task in the near future. Until then, please feel free to communicate with me at daniel.divenere@dubsado.com instead of opening a Github issue.

Thank you for understanding.
